// === Module: Data Source ===
// Açıklama: Rastgele seçilecek logoların havuzu.
// Performans: Sabit veri olduğu için bileşen dışında tanımlandı.

export const logoPool = [
  "/img/logos/ajax.png",
  "/img/logos/arsenal.png",
  "/img/logos/astonvilla.png",
  "/img/logos/atleticomadrid.png",
  "/img/logos/barcelona.png",
  "/img/logos/bayern.png",
  "/img/logos/chelsea.png",
  "/img/logos/dortmund.png",
  "/img/logos/everton.png",
  "/img/logos/fb.png",
  "/img/logos/fiorentina.png",
  "/img/logos/gs.png",
  "/img/logos/inter.png",
  "/img/logos/juventus.png",
  "/img/logos/lazio.png",
  "/img/logos/leipzig.png",
  "/img/logos/leverkusen.png",
  "/img/logos/lille.png",
  "/img/logos/liverpool.png",
  "/img/logos/lyon.png",
  "/img/logos/manu.png",
  "/img/logos/marsilya.png",
  "/img/logos/mcity.png",
  "/img/logos/milan.png",
  "/img/logos/monaco.png",
  "/img/logos/napoli.png",
  "/img/logos/newcastle.png",
  "/img/logos/psg.png",
  "/img/logos/psv.png",
  "/img/logos/realmadrid.png",
  "/img/logos/roma.png",
  "/img/logos/Sevillafc.png",
  "/img/logos/tottenham.png",
  "/img/logos/valencia.png",
  "/img/logos/besiktas.png",
];
